firmware/Makefile
A hopefully simple fix for #1
We can update `BOARD` after `rules.mk` is parsed to adjust the build directory to be removed when executing the clean target.
Because other variables all use immediate assignment `:=` they're not effected when we make this change to `BOARD`.
But due to the way make works, when it goes to actually execute the `clean` target on the second pass `BOARD` is now set to `_build` like we want.
=> apollo: Fix clean makefile target

apollo_fpga/__init__.py, pyproject.toml
This is necessary to force the release of the USB device without waiting on the Python garbage collector. Without intentionally releasing the USB device, programming fails under Windows because an earlier ApolloDebugger instance already has the USB device open from querying the board version.
=> Add close method to ApolloDebugger

firmware/src/jtag_tap.c
Without this patch, the interactive test fails on the ID register read:
Debug module:    ✗ FAILED    (register 1 was 0xA8455354, not expected 0x54455354)
After applying the patch, rebuilding and flashing the updated apollo, the test now passes.
=> Apply miek jtag fix.

apollo_fpga/__init__.py, firmware/src/boards/daisho/tusb_config.h, firmware/src/boards/luna_d11/dfu.c, firmware/src/boards/luna_d11/tusb_config.h, firmware/src/boards/luna_d21/dfu.c, firmware/src/boards/luna_d21/tusb_config.h, firmware/src/boards/qtpy/apollo_board.h, firmware/src/boards/qtpy/board.mk, firmware/src/boards/qtpy/debug_spi.c, firmware/src/boards/qtpy/dfu.c, firmware/src/boards/qtpy/fpga.c, firmware/src/boards/qtpy/jtag.c, firmware/src/boards/qtpy/led.c, firmware/src/boards/qtpy/platform_jtag.h, firmware/src/boards/qtpy/spi.c, firmware/src/boards/qtpy/spi.h, firmware/src/boards/qtpy/tusb_config.h, firmware/src/boards/qtpy/uart.c, firmware/src/boards/qtpy/usb_descriptors.c, firmware/src/boards/samd11_xplained/dfu.c, firmware/src/boards/samd11_xplained/tusb_config.h
This adds support for Apollo on https://www.adafruit.com/qtpy boards. I've been using it with an OrangeCrab 0.2.1
I've updated to latest tinyusb to support that board. There are some API changes related to DFU which I've updated, though haven't tested on any other boards.
=> Add support for Adafruit qtpy atsamd21 board

firmware/Makefile, firmware/src/boards/luna_d11/dfu.c, firmware/src/boards/luna_d11/tusb_config.h, firmware/src/boards/luna_d21/dfu.c, firmware/src/boards/luna_d21/tusb_config.h, firmware/src/boards/samd11_xplained/dfu.c, firmware/src/boards/samd11_xplained/tusb_config.h
Switch to TinyUSB 0.14.0
updates lib/tinyusb submodule to 0.14.0 and adapts board source files accordingly
firmware for daisho couldn't be build to to missing bsp in TinyUSB
current TinyUSB submodule makes building for ESP32-S2 quite hard
=> modules: switch to tinyusb 0.14.0

apollo_fpga/commands/cli.py, apollo_fpga/ecp5.py, apollo_fpga/jtag.py
Improves flashing speed by:
- Ignoring unused SPI responses.
- Avoiding an unnecessary check.
- Performing partial erases when programming.
#9 implements partial erases too, but the version in this PR is also able to use mixed eraseblock sizes.
Offset writes and reads are intentionally left out of this PR, but it's open for discussion.
=> apollo_fpga: Flash programming speed improvements

apollo_fpga/__init__.py, apollo_fpga/commands/cli.py, apollo_fpga/gateware/__init__.py, apollo_fpga/gateware/advertiser.py, firmware/src/boards/cynthion_d11/fpga_adv.c, firmware/src/boards/cynthion_d21/fpga_adv.c, firmware/src/boards/daisho/fpga_adv.c, firmware/src/boards/qtpy/fpga_adv.c, firmware/src/boards/samd11_xplained/fpga_adv.c, firmware/src/fpga_adv.h, firmware/src/main.c, firmware/src/usb_switch.c, firmware/src/vendor.c
Apollo firmware will keep the USB switch handed over to the FPGA as long as the gateware keeps advertising its usage through the `FPGA_ADV` pin (`FPGA_INT`). When these messages stop arriving, Apollo will take over the port. If the ads resume, the port will not be handed off to the FPGA again until a "honor FPGA_ADV" (`0xc2`) vendor request arrives.
Additionally, the host tools can request a gateware to hand off the USB port to Apollo if the necessary request is available.
- firmware: Adds `HONOR_FPGA_ADV` vendor request (`0xc2`)
- apollo_fpga: Use `REQUEST_APOLLO_ADV_STOP` (`0xf0`) to enumerate Apollo
Merge in block with:
- https://github.com/greatscottgadgets/luna/pull/225
- https://github.com/greatscottgadgets/luna/pull/226
- https://github.com/greatscottgadgets/cynthion/pull/23
=> Add support for one-way FPGA advertisement pin

firmware/src/boards/cynthion_d11/led.c, firmware/src/boards/cynthion_d21/led.c, firmware/src/led.h
This PR allows static bitmasks to be applied to the LEDs, as well as dynamic blink patterns.
Conveniently, none of the existing blink patterns have enum values of less than the maximum bitmask.
Required for Cynthion factory test.
=> Support static bitmasks as LED patterns

pyproject.toml
Submodules (`protocol`, `support`, `commands`, `gateware`) were not installed in certain scenarios.
=> pyproject.toml: fix installation issues

apollo_fpga/__init__.py, apollo_fpga/commands/cli.py, apollo_fpga/ecp5.py, apollo_fpga/gateware/flash_bridge.py, pyproject.toml
This PR adds a command to Apollo CLI (`apollo flash-fast`) for flash programming. This command first programs a  gateware SPI bridge to the FPGA and then uses it to access the configuration SPI flash.
=> cli: add flash-fast command

firmware/src/boards/cynthion_d11/apollo_board.h
=> firmware: Ignore button with shared pin

firmware/src/boards/daisho/usb_descriptors.c, firmware/src/mcu/samd11/usb_descriptors.c, firmware/src/vendor.c
Add Microsoft OS 1.0 descriptor for the DFU runtime interface.
The CDC interface is recognized by Windows as a serial port already. This change makes the DFU runtime appear as a WinUSB device.
=> firmware: add WCID descriptors

firmware/src/boards/cynthion_d11/fpga.c, firmware/src/boards/cynthion_d11/fpga_adv.c, firmware/src/boards/cynthion_d11/led.c, firmware/src/boards/cynthion_d21/fpga.c, firmware/src/boards/cynthion_d21/fpga_adv.c, firmware/src/boards/cynthion_d21/led.c, firmware/src/boards/daisho/fpga_adv.c, firmware/src/boards/daisho/led.c, firmware/src/boards/qtpy/fpga.c, firmware/src/boards/qtpy/fpga_adv.c, firmware/src/boards/qtpy/led.c, firmware/src/boards/samd11_xplained/fpga.c, firmware/src/boards/samd11_xplained/fpga_adv.c, firmware/src/boards/samd11_xplained/led.c, firmware/src/debug_spi.c, firmware/src/fpga.c, firmware/src/fpga.h, firmware/src/fpga_adv.h, firmware/src/jtag.c, firmware/src/led.h, firmware/src/main.c, firmware/src/usb_switch.c, firmware/src/usb_switch.h, firmware/src/vendor.c
=> firmware: implement new LED scheme

firmware/src/boards/cynthion_d11/fpga.c, firmware/src/boards/cynthion_d11/fpga_adv.c, firmware/src/boards/cynthion_d21/fpga.c, firmware/src/boards/cynthion_d21/fpga_adv.c, firmware/src/boards/daisho/fpga_adv.c, firmware/src/boards/qtpy/fpga.c, firmware/src/boards/qtpy/fpga_adv.c, firmware/src/boards/samd11_xplained/fpga.c, firmware/src/boards/samd11_xplained/fpga_adv.c, firmware/src/fpga.c, firmware/src/fpga.h, firmware/src/fpga_adv.h, firmware/src/jtag.c, firmware/src/vendor.c
Whenever the FPGA is taken offline, stop allowing it to take over the shared USB port. This prevents a later FPGA configuration from taking over the port before it is explicitly allowed to do so.
This fixes a bug introduced in #50 in which a port handoff could be inappropriately deferred from one FPGA configuration (which does not request the port) to a later configuration (which does request the port):
```
$ blinky.py
$ bulk_speed_test.py (modified to use CONTROL)
INFO    | __init__    | Building and uploading gateware to attached Cynthion r1.3...
Traceback (most recent call last):
File "/home/mossmann/src/apollo/apollo_fpga/ecp5.py", line 467, in configure
status = self._read_status()
^^^^^^^^^^^^^^^^^^^
File "/home/mossmann/src/apollo/apollo_fpga/ecp5.py", line 515, in _read_status …
```
=> firmware: Disallow FPGA takeover of USB port

apollo_fpga/__init__.py, apollo_fpga/commands/cli.py, firmware/Makefile, firmware/src/vendor.c
=> Add firmware version string and USB API versioning

apollo_fpga/gateware/advertiser.py, apollo_fpga/gateware/flash_bridge.py
Update descriptors for flash bridge gateware.
=> Flash bridge descriptor updates

firmware/src/mcu/samd11/usb_descriptors.c, firmware/src/vendor.c
Add a property to treat the device as `USBDevice`, defined here: https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/supported-usb-classes
=> firmware: add Microsoft OS 1.0 extended properties

apollo_fpga/__init__.py
Under Windows, libusb sends the vendor request with the recipient set to interface 0 by default. Claiming the appropiate interface before seems to work.
=> apollo_fpga: fix handing off USB port to Apollo under Windows

firmware/src/boards/cynthion_d11/fpga_adv.c, firmware/src/fpga_adv.h
Because there is no crystal for the microcontroller on Cynthion, UART baud rate mismatch can result in a failure to receive FPGA advertisements. We only need one type of advertisement, so we're replacing the UART receiver with simpler pulse detection. We require a minimum number of pulses per measurement period in order to ignore glitches that occur during FPGA configuration.
=> firmware.fpga_adv: replace UART reception with edge counter

firmware/src/boards/cynthion_d11/apollo_board.h, firmware/src/boards/cynthion_d11/fpga_adv.c, firmware/src/boards/cynthion_d11/led.c, firmware/src/boards/cynthion_d21/apollo_board.h, firmware/src/boards/cynthion_d21/jtag.c, firmware/src/button.c, firmware/src/usb_switch.c
Also support the button on older Cynthions (r0.3-r0.5). The button is referred to as PROGRAM in the source code to match newer Cynthions but is labeled DFU on silkscreen.
This fixes #21 for board revisions r0.3-r0.4 but does not fix r0.1-r0.2. In theory this type of solution could work for r0.1-r0.2, but my initial tests were not successful. For now, Sideband PHY usage is unsupported on r0.1-r0.2.
See also the similar fix for Saturn-V: https://github.com/greatscottgadgets/saturn-v/issues/15
=> Hold Sideband PHY RESET low on older Cynthions

apollo_fpga/gateware/advertiser.py
Ditch the old UART transmitter approach.
=> gateware: `ApolloAdvertiser` generates rising edges now

firmware/CMakeLists.txt
The Pico build broke after merging #34 because #32 had been merged since the last rebase of #34.
=> firmware: add board_rev.c to Pico build

apollo_fpga/__init__.py, apollo_fpga/commands/cli.py
This change avoids `apollo` disrupting the FPGA operation when executing the `info` or `flash-info` commands.
A `--force-offline` option is added to keep the existing behavior.
=> apollo_fpga.commands: avoid automatic FPGA takeover for info commands

CHANGELOG.md
This PR adds a changelog to the repo based on the format documented at: [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)
I must admit the entries I've added for the changes since `v1.0.0` aren't particularly inspired, ideally this document would also include some more information about the "why" of things so it can provide a bridge between git commit logs and the story behind those commits.
=> Add a changelog to the repo

pyproject.toml
This PR:
1. Adds support for the `setuptools-git-versioning` plugin that uses repository tags to automatically manage package release versions.
2. Updates the package description.
3. Removes `Topic :: Security` from the package metadata.
4. Adds `issues` to the Project URL's
5. Replaces `luna-usb` git dependency with a release version.
=> Update pyproject for release

apollo_fpga/gateware/flash_bridge.py
=> apollo_fpga.gateware: do not trigger reconfiguration using `flash --fast`

apollo_fpga/__init__.py, firmware/Makefile, firmware/src/boards/cynthion_d11/apollo_board.h, firmware/src/boards/cynthion_d21/apollo_board.h, firmware/src/boards/daisho/apollo_board.h, firmware/src/boards/daisho/usb_descriptors.c, firmware/src/boards/qtpy/apollo_board.h, firmware/src/boards/raspberry_pi_pico/apollo_board.h, firmware/src/boards/samd11_xplained/apollo_board.h, firmware/src/mcu/rp2040/usb_descriptors.c, firmware/src/mcu/samd11/usb_descriptors.c, misc/54-apollo.rules
Implements part of the plan in #86
=> Use pid.codes test VID/PID for non-Cynthion boards

apollo_fpga/gateware/flash_bridge.py
Use the new `apollo_gateware_phy` property introduced in greatscottgadgets/luna#269.
Fixes #94.
=> gateware.flash_bridge: fix port in platforms that share it with Apollo

apollo_fpga/__init__.py, apollo_fpga/gateware/flash_bridge.py, pyproject.toml
On Windows the `usb1` Python package installs the libusb1 dll within the `usb1` module directory but can not locate it to create a backend unless the module directory is added to the system `PATH` environment variable. 
This PR modifies the `ApolloDebugger._find_device()` static method to, on Windows, obtain the backend by passing the location of the installed `libusb-1.0.dll` to `libusb1.get_backend()` and then passing that backend to `usb.core.find()`.
This PR also modifies the other usage of `usb.core.find()` in `FlashBridgeConnection`to use `ApolloDebugger._find_device()` instead.
It's important to note that, for future work on Apollo, the `usb.core.find()` method should no longer be used if Windows compatibility is to be maintained!
This is a companion PR to the one in Cynthion: …
=> On Windows, create the libusb1 backend explicitly by specifying the installed location of libusb-1.0.dll

apollo_fpga/__init__.py
We may wish to remove this or hide it behind a `--verbose` option in the future.
=> apollo_fpga: Add ADC reading to print_info()

.github/workflows/host.yml, pyproject.toml
This works around a pdm bug (#3271) and removes a "Provides-Extra" listing on PyPI.
=> Remove py_ci installation option
